export const CHANGE_MENU_VISIBILITY = "CHANGE_MENU_VISIBILITY";

export const CHANGE_DROPDOWN_VISIBILITY = "CHANGE_DROPDOWN_VISIBILITY";

export const CHANGE_SETTING_INPUT = "CHANGE_SETTING_INPUT";

export const CHANGE_LEVEL_INPUT = "CHANGE_LEVEL_INPUT";

export const CHANGE_THEME_INPUT = "CHANGE_THEME_INPUT";

export const MAKE_AJAX = "MAKE_AJAX";

export const MAKE_CAMPAIGN = "MAKE_CAMPAIGN";
